### ISSUE TITLE
use doesBucketExist instead of listBuckets

### ISSUE THREAD

**Issue by fantapop** [WowzaMediaSystems/wse-plugin-s3upload#10]
On line [ModuleS3Upload.java#410](https://github.com/WowzaMediaSystems/wse-plugin-s3upload/blob/master/src/com/wowza/wms/plugin/s3upload/ModuleS3Upload.java#L410) you check to make sure the bucket exists.  You should use ```s3client.doesBucketExist()```  instead which will allow you to only require ListBucket permission on the specific bucket instead of a more encompassing unnecessary permission of ListAllMyBuckets.  It will also simplify the code and remove the need for a loop.

**Comment by rogerlittin** [comment]
`doesBucketExist();` only checks to see if the bucket name exists anywhere on S3 and not if the user owns it or has access to it. This is the reason we have been using `listBuckets();` up until now.

We are currently working on a new build that replaces the old AWS SDK methods with the newer methods and are also going to change to using `s3Client.getBucketLocation(bucketName);` which does check if the user has access to the bucket and we can check that the correct region has been set (required for the newer SDK calls).

**Comment by rogerlittin** [comment]
This has now been updated and merged into master. Please see the version.txt for the change details.
The following permissions are required:
(bucket)
ListBucket for bucket permission check and versioning
(objects)
PutObject
PutObjectAcl if ACLs are specified
AbortMultipartUpload if resume uploads is disabled
