### ISSUE TITLE
Cross-account permissions

### ISSUE THREAD

**Issue by nrobst** [WowzaMediaSystems/wse-plugin-s3upload#11]
When writing to an S3 bucket in a different account, it would be good to be able to set a canned ACL on the uploaded object: https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#canned-acl

Perhaps through the use of a parameter - s3UploadCannedACL=bucket-owner-full-control (for example)?

Thanks!

**Comment by rogerlittin** [comment]
This has now been updated and merged into master. Please see the version.txt for the change details.
