### ISSUE TITLE
Support for IAM roles instead of using access keys

### ISSUE THREAD

**Issue by j4y** [WowzaMediaSystems/wse-plugin-s3upload#12]
It would improve security if we could use this plugin without having to put the AWS access key and secret key in the `Application.xml`.  Amazon Web Services has a feature that uses roles to gain access based on the EC2 instance it is running on.

Stackoverflow post with example java code:
https://stackoverflow.com/questions/44062813/aws-s3-upload-without-access-and-secret-key-in-java

I tried removing the access key and secret key from my configuration, but the plugin checks for this and did not try to upload.

**Comment by rogerlittin** [comment]
Hi,

We have a branch in development to provide support for IAM roles. See https://github.com/WowzaMediaSystems/wse-plugin-s3upload/tree/IAM_Support

**Comment by rogerlittin** [comment]
This has now been updated and merged into master. Please see the version.txt for the change details.
