### ISSUE TITLE
versioned files are not getting copied to s3

### ISSUE THREAD

**Issue by fantapop** [WowzaMediaSystems/wse-plugin-s3upload#13]
I've set the configuration option s3UploadDelay in an effort to be more resilient to network issues.   I'd like to allow recovering a stream if its within 2 minutes of the ending.  When I test this out however, I see the _0, _1, etc.. recordings on the wowza server but when the delay is up, only the non-versioned entry is copied into s3.  Am I doing this wrong? or is this not how it was intended to work?

**Comment by fantapop** [comment]
I was able to get what I needed working using the autorecord plugin which unlocks using the StreamRecorder which can append to files.  In this case I don't need to upload multiple versions for this use case.  If this is not a bug, feel free to close.

**Comment by rogerlittin** [comment]
The internal recording option is set to version by default. There is a property to switch it to append.
