### ISSUE TITLE
403 error downloading plugin

### ISSUE THREAD

**Issue by j4y** [WowzaMediaSystems/wse-plugin-s3upload#14]
I'm getting a 403 forbidden error downloading the plugin:

https://www.wowza.com/downloads/forums/collection/wse-plugin-s3upload.zip

```
Forbidden
You don't have permission to access /downloads/forums/collection/wse-plugin-s3upload.zip on this server.

Apache Server at www.wowza.com Port 443
```

**Comment by rogerlittin** [comment]
Hi,

It looks like our server was cacheing some bad responses. The cache has been cleared now and the download should work. Please try again and let us know if you still see any issues.

-Roger.
