### ISSUE TITLE
incorrect bucket region warning when using default region settings

### ISSUE THREAD

**Issue by j4y** [WowzaMediaSystems/wse-plugin-s3upload#16]
I'm using this plugin (Build 50) with Wowza Streaming Engine 4.7.5 and it seems to be logging a warning incorrectly:

```
ModuleS3Upload.onAppStart: [whale_videorecording/_definst_] bucket region doesn't match configured region. (b:c)[us-east-1:null]
```
Both my EC2 instance and my S3 Bucket are configured to be in US East.  I am using the `s3UploadUseDefaultRegion` option, which is enabled by default.  The only setting I am using is the `s3UploadBucketName` option.

**Comment by rogerlittin** [comment]
Hi,

I'm pretty sure that is just a warning during the bucket check to say that the region name hasn't been configured and it should have been safe to ignore. Saying that, I have updated the code to set the regionName variable when the default region is being used so the bucket check should still work. Please update and see if that resolves your issue.

Thanks,

Roger.
