### ISSUE TITLE
Question regarding implementation

### ISSUE THREAD

**Issue by paluh** [WowzaMediaSystems/wse-plugin-s3upload#17]
Hi,

Thanks for sharing this plugin and its source code. I'm writing plugin for processing recordings too

* Do you think that it is possible to take different route and use `ILiveStreamRecordManagerActionNotify` and `onStopRecord` method instead of `IMediaWriterActionNotify`?

* In my subclass of `ILiveStreamRecordManagerActionNotify` in `onStopRecord` I want to spawn external process like:

   ```java
   p = Runtime.getRuntime().exec(processor);
   p.waitFor();
   ```
  Do you think that this can block some important thread or it is OK to do this in this place?

Sorry if my questions are rather basic and somewhat related to my a bit lacking Java skills ;-)

P.S.
Of course I'm going to open source my plugin as well...

**Comment by rogerlittin** [comment]
Would need to check, but I think that event is only called when the recorder is shut down. it won't be called if the recording is segmented. 

Either way, blocking the thread for any length of time is a bad idea. The same goes for any other event listener.
