### ISSUE TITLE
 Occasionally a NoSuchUpload error occurs.

### ISSUE THREAD

**Issue by kyungwon-cho** [WowzaMediaSystems/wse-plugin-s3upload#18]
When resuming multipart upload, the following error occurs. Target is using minio.

com.amazonaws.services.s3.model.AmazonS3Exception: The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchUpload; Request ID: 3L137; S3 Extended Request ID: 3L137), S3 Extended Request ID: 3L137

**Comment by akeller** [comment]
Stale.
