### ISSUE TITLE
ModuleS3Upload compatibility with others S3 vendors

### ISSUE THREAD

**Issue by multimediaSGT** [WowzaMediaSystems/wse-plugin-s3upload#19]
When I use ModuleS3Upload on Wowza 4.7.6, with AWS Java SDK 1.11.495, it throws this exception in the log :

ModuleS3Upload.onAppStart [javitest/_definst_] exception: Unable to find a region via the region provider chain. Must provide an explicit region in the builder or setup environment to supply a region.: com.amazonaws.SdkClientException: Unable to find a region via the region provider chain. Must provide an explicit region in the builder or setup environment to supply a region.|at com.amazonaws.client.builder.AwsClientBuilder.setRegion(AwsClientBuilder.java:462)|at com.amazonaws.client.builder.AwsClientBuilder.configureMutableProperties(AwsClientBuilder.java:424)|at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)|at com.wowza.wms.plugin.s3upload.ModuleS3Upload.onAppStart(ModuleS3Upload.java:495)|at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

We need know if this module is fully supported with other S3 compatible services (not Amazon itself). If it's the case, how is the procedure to define the region, and configure an enviroment to replace the region. Thanks.

**Comment by rogerlittin** [comment]
The region name is set using the `s3UploadRegion` property. Valid region names are as listed here, https://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region. If the region name is not set, and `s3UploadUseDefaultRegion` is set to true, then the module will attempt to get the region from the EC2 instance (if it's running on an EC2 instance) or it will use the default region which is `us-east-1`. If the region is still not set then the AWS SDK will attempt to discover the region using the `DefaultAwsRegionProviderChain` which uses Environment Variables or System Properties or AWS Profile or EC2 Instance Metadata, in that order.

As for compatibility with other S3 compatible services, The module uses the official AWS SDK so if the service is fully compatible with the AWS SDK then it should work. You would have to ask your service provider or Amazon about this.
