### ISSUE TITLE
Functionality for a EndPoint connection in a private enviroment

### ISSUE THREAD

**Issue by multimediaSGT** [WowzaMediaSystems/wse-plugin-s3upload#20]
Hi

We have a Hitachi Machine which is managed with the Amazon (AWS SDK) APIs over .NET application. Our machine is 100% compatible with AWS protocol, but that machine is in a private hosting (it’s not Amazon Cloud), then I can’t connect with the ‘region’ properties of the S3Upload plugin.

Reviewing the source code, I have seen that property S3UploadEndpoint could establish a direct connection (endpoint), this is the way we do to connect from the AWS APIs over .Net in this environment, and it’s working 100%. I think this functionality isn't fully implemented on the source because the source is more oriented to work with connection over the Amazon Cloud sites.

I would like to know if you will be able to develop this functionality, because my java skills are limited.

Thanks, Regards.

**Comment by seongjae** [comment]
I have the same problem. 
I tried to build this project but I have a dependency problem with the wowza library.

How do I build it?

@multimediaSGT did you fix it?

**Comment by akeller** [comment]
Stale.
