### ISSUE TITLE
Using variables for Properties value

### ISSUE THREAD

**Issue by midorinet** [WowzaMediaSystems/wse-plugin-s3upload#21]
Hi

I need to use a for s3UploadFilePrefix

To have something like

```
  			<Property>
    			<Name>s3UploadFilePrefix</Name>
    			<Value>${com.wowza.wms.context.Application}</Value>
  			</Property>
```

However variables is not supported. Is there any way to achieve this?

**Comment by rogerlittin** [comment]
That would need to be added as a new feature.  You can do that and submit a pull request, or we can add it in a future update.
