### ISSUE TITLE
TV Channel-Style Streaming Wowza streaming engine

### ISSUE THREAD

**Issue by hasanbajwa** [WowzaMediaSystems/wse-plugin-s3upload#24]
I have recently purchased the Wowza streaming engine, and I have created this with the AMS server-side and run through AES encryption. At the start, it starts working and after a few seconds this error message "Adobe Flash Player is having trouble, either install the latest version or, if I have the latest version, turn on Flash Player".
I verified latest Flash Player is installed on my PC
I am using Window 10
when I contact Wowza and describe this problem
says it's an Adobe problem.
What to do? Any suggestions?
kindly visit this and tell me any solution
[https://www.tvnewslivestream.com/](https://www.tvnewslivestream.com/)

**Comment by rogerlittin** [comment]
Hi,

Most browsers have either blocked flash completely or require you to enable it specifically for each website that you want to use flash with.  To fix the issue, you will need to use a player that doesn't require flash.  

As this isn't an issue with this plugin, I'm closing this issue.

**Comment by hasanbajwa** [comment]
can you suggest to me players that don't require flash

**Comment by dfernandezm** [comment]
@hasanbajwa  HLJS https://github.com/video-dev/hls.js/, JWPlayer, VideoJS  https://videojs.com/
