### ISSUE TITLE
Support for s3 compatible object storage

### ISSUE THREAD

**Issue by isss802** [WowzaMediaSystems/wse-plugin-s3upload#25]
Would it be possible to specify endpoints so that S3 compatible object storage can be supported?

For example, object storage like Linode.

https://www.linode.com/docs/products/storage/object-storage/guides/urls/

**Comment by rogerlittin** [comment]
It possibly can be done but you would need to make a few edits to the code.

- Move `endpoint = props.getPropertyStr("s3UploadEndpoint", endpoint);` on line 383 out of the if statement so it is before the if statement.
- Wrap lines 440 - 465 where the region check and builder.withRegion is called, in the else part of an if-else statement with the following
```java

if (endpoint != null && regionName != null)
{
    builder.withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration(endpoint, regionName));
}
else
...
```

This is untested so you may run into some other issues.
