### ISSUE TITLE
Stream not deleting

### ISSUE THREAD

**Issue by tageses** [WowzaMediaSystems/wse-plugin-s3upload#8]
When streaming a stream "myStream", this gets recorded as myStream.mp4 and uploaded to S3. 
When file uploading to S3 bucket, in local FS creating file myStream.mp4.upload, but after uploaded to S3, myStream.mp4 not deleting from local FS.
Properties s3UploadDeleteOriginalFiles and s3UploadDeletOriginalFiles set to TRUE )))
![image](https://user-images.githubusercontent.com/28482950/30943852-80f300de-a3fc-11e7-83e5-dfecab2eb49e.png)

**Comment by rogerlittin** [comment]
This should now be fixed. There was an issue where the wrong file name was being used if a file prefix is set.

Note: due to caching, it may take up to 24 hours for the updated zip file to become available.
