### ISSUE TITLE
Clarify which permissions are needed on the S3 buckets to allow uploads (and only uploads).

### ISSUE THREAD

**Issue by titpetric** [WowzaMediaSystems/wse-plugin-s3upload#9]
Use case: I don't want to open full permissions to the S3 bucket(s) which Wowza would have permissions to upload to, what is the minimal set of permissions required to allow uploads to a S3 bucket?

Best,
Tit

**Comment by fantapop** [comment]
Based on my testing the required list is currently:

On your upload bucket:
---------------------
PutObject
AbortMultipartUpload

On *
---------------------
ListAllMyBuckets



I opened issue https://github.com/WowzaMediaSystems/wse-plugin-s3upload/issues/10 to remove requirement for ListAllMyBuckets

**Comment by rogerlittin** [comment]
You also need `getObject`permission on your bucket if you have versioning enabled. As per #10, we are creating a new build that will allow the permissions to be tightened further.

**Comment by fantapop** [comment]
It looks like you need ```ListBucket``` and not ```GetObject``` based on my tests.

**Comment by rogerlittin** [comment]
This has now been updated and merged into master. Please see the version.txt for the change details.
The following permissions are required:
(bucket)
ListBucket for bucket permission check and versioning
(objects)
PutObject
PutObjectAcl if ACLs are specified
AbortMultipartUpload if resume uploads is disabled
